package hbm.planner.scenarioTest;

import hbm.planner.dataobject.NewProjectData;
import hbm.planner.dataobject.SignUpData;
import hbm.planner.utility.Browser;
import hbm.web.pageobject.LandingPage;
import hbm.web.pageobject.UserHomePage;

import org.openqa.selenium.support.PageFactory;
import org.testng.annotations.Test;

public class HBMRedwireEdge extends Browser{
	
	@Test(dataProvider="loginData", dataProviderClass=SignUpData.class)
	public void redwireMacLogin(SignUpData signUpData){
		LandingPage homepage = PageFactory.initElements(driver, LandingPage.class);
		homepage.loginExistingUser(signUpData);
	}
	
	@Test(dataProvider="projectDataODT", dataProviderClass=NewProjectData.class, dependsOnMethods="redwireMacLogin")
	public void newProdjectmac(NewProjectData newProjectData){
		UserHomePage home = PageFactory.initElements(driver, UserHomePage.class);
		home.createEmptyProject(newProjectData)
		.addARoom(6, "", "Living room")
		.edit2DWallPropertiesDev(114, 0, "30", "", "", "")
		.edit2DWallPropertiesDev(-114, 0, "30", "", "", "")
		.edit2DWallPropertiesDev(0, 230, "30", "", "", "")
		.edit2DWallPropertiesDev(0, -230, "30", "", "", "")
//		.exteriorDev(0, 0, 1, "200")
		.editTwoDWallDimensionDev(100, 225, "201 cm", "550", "left")
		.editTwoDWallDimensionDev(100, -225, "550 cm", "900", "right")
		.editTwoDWallDimensionDev(465, 50, "432 cm", "591", "above")
		.editTwoDWallDimensionDev(-465, 100, "591 cm", "750", "below")		
		.wallDev("HBMMac")
		.editTwoDWallDimensionDev(0, -90, "235 cm", "300", "above")
		.addAProductDev("4883", -50, -70)
		.addAProductDev("4883", 50, -70)
		.addAProductDev("4883", -150, 0)
		.addAProductFromInfoDev("maisondumonde_147876", 190, 185)
		.addAProductFromBrandsDev("Seven Seas Reclining Sofa with Console in Cognac", 0, 185)
	
		.addAProductWithoutFilterDev("Kitchen set I shape l280", -310, 110)	//changes -320 to -300 and 85 to 110
		.threeDView()
		.edit3DWallPropertiesDev(-130, 0, "Wall and floor tile", 0, "9363", 1)
		.edit3DWallPropertiesDev(-450, 250, "Wall and floor tile", 0, "9363", 1)
		.verifyLogoLinkDev(0, 200)
		.save()
		.edit3DWallPropertiesDev(150, 0, "Wallpaper", 0, "8754", 0)
		.verify3DWallPropertiesDev(-450, 250, "Wall and floor tile", 0, "9363", 1)
		.fpRotateDev(46, "right")
		.addAProductDev("899", 100, -120)	
		.save()
		.closePlanner()
		.editLatestProject()
		.verify3DWallPropertiesDev(150, 0, "Wallpaper", 0, "8754", 0)
		.verifyLogoLinkDev(0, 200)
		.closePlanner()
		.goToMyProjects()
		.openOwnProject(1)
//		.verifyOverviewTabPage("own", 1, 4, "66", 0, 0, 2, 0)
		.openProject()
		.threeDView()
		.addAProductDev("9424", 100, 100)
		.fpRotateDev(10, "left")
		.fpRotateDev(10, "up")
		.addAProductSearchDev("Dormitorio aura", -150, -20)  // changes from 0 to -20
		.addAProductDev("582", 350, 50)
		.addAProductDev("12603", 200, 100)
		.addAProductDev("8873", 130, 20)
		.snapshot3D("before adding floor: setting 2", 1)		
		.twoDView()
		.zoomOut(6)
		.snapshot2D("Mtl All Dim Large Name", "all", true, true, "large", true, false, false, false)
		.addAProductSearchDev("PBR_COUCH_PUBLI", 210, 90)		
		.threeDView()		
		.fpRotateDev(25, "down")
		.fpRotateDev(25, "right")
		.edit3DWallPropertiesDev(130, -230, "Wall and floor tile", 0, "4063", 0)
		.edit3DWallPropertiesDev(-265, -210, "Wall and floor tile", 0, "4063", 0)
		.verify3DWallPropertiesDev(130, -230, "Wall and floor tile", 0, "4063", 0)
		.save()
		.snapshot3D("setting 3", 2)		
		.editGenericPropertiesDev(140, -155, "55", "200", "42", "Metal", 0, "1261")
		.verifyGenericPropertiesDev(140, -155, "55.0 cm", "200.0 cm", "42.0 cm", "1261")
		.realisticImageClick()
		.getStarted()
		.setBackground(1, true)
		//.setSunPosition("286")
		.displayPeople(true)
		.lensOption(true, 0)
		.clickGenerateButton()
		.sendHQImageRequest("small")
		.closeHQMessage()
		.addFloorOrBasementOrPlan(1, 0, "300", "")
		.twoDView()
		.addAProductDev("2629", 300, 0)
		.save()
		.edit2DWallPropertiesDev(0, 125, "", "", "200", "")
		.addAProductDev("Rooftop Window", 200, 100)
		.addAProductSearchDev("Rooftop Window", 0, 100)		
		.editDoorWinPropertiesDev(200, 80, "", "200", "", 0, 0)
		.verifyDoorWinPropertiesDev(200, 80, "100.0 cm", "200.0 cm", "")
		.verifyDoorWinPropertiesDev(0, 80, "100.0 cm", "80.0 cm", "")
		.addAProductSearchDev("DSPBR_test_spec_transp_map", 350, -110)
		.threeDView()
		.editFloorPropertiesDev(0, -40, "Living room", "Carpet", "7883", 0)
		.verifyFloorPropertiesDev(0, -40, "Living room", "Carpet", "7883", 0)
		.save()
		.closePlannerReturnProjectPage()
		.openProject()
		.changeActiveFloor("First floor")
		.fpRotateDev(45, "right")
		.addAProductSearchDev("Silla phantom", 215, -65)
		.fpRotateDev(10, "right")
		.save()
		.realisticImageClick()
		.getStarted()
		.setBackground(1, true)
		//.setSunPosition("286")
		.displayPeople(true)
		.lensOption(true, 0)
		.clickGenerateButton()
		.sendHQImageRequest("small")
		.closeHQMessage()
		.snapshot3D("setting 1", 0)
		.fpRotateDev(40, "left")
		.fpRotateDev(7, "up")
		.firstPersonView()
		.snapshot()
		.twoDView()
		.zoomOut(5)
		.roomSeparationDev("HBMMacSep1")
		.editFloorPropertiesDev(-290, 200, "Kitchen", "", "", 0)
		.editFloorPropertiesDev(-290, 200, false, true)
		.verifyFloorPropertiesDev(-290, 200, false, true)
		.snapshot2D("FirstFloor", "All", true, true, "Large", true, true, false, false)
		.threeDView()
		.changeActiveFloor("Ground floor")						
		.snapshot3D("setting 4", 3)
		.save()
		.closePlannerReturnProjectPage()
		.openProject()
		.changeProjectDetails("EdgeProject", "Apartment", "Dreamed project")
		.verifyProjectDetails("EdgeProject", "Apartment", "Dreamed project", 2, 9, 131.67)
		.verify3DWallPropertiesDev(440, 90, "Wall and floor tile", 0, "4063", 0)
		.verifyGenericPropertiesDev(80, -170, "270.0 cm", "133.9 cm", "136.4 cm", "")
		.verifyGenericPropertiesDev(-400, 120, "250.0 cm", "280.0 cm", "66.5 cm", "")
		.verifyLogoLinkDev(200, 200)
		.changeActiveFloor("First floor")
		.snapshot3D("Floor Hole: setting 5", 4)
		.verifyFloorPropertiesDev(60, 65, "Living room", "Carpet", "7883", 0)
		.verifyFloorPropertiesDev(60, 65, false, false)
		.twoDView()
		.zoomOut(1)
		.verify2DWallPropertiesDev(-125, 353, "30 cm", "300 cm", "810 cm", 1, "200 cm", "140 cm")
		.editBayDimensionDev(100, 275, 209, 200)
		.verifyBayDimensionDev(100, 275, 200, 1)
		.verifyFloorPropertiesDev(-355, 150, false, true)
		.threeDView()
		.save()
		.closePlannerReturnProjectPage()
		.verifyProjectDetails(2, 9, "132 m\u00B2", 0, 0)
		.goToProductsTab()
		.checkProductList(5,"2,1,1,1")
		.goToImagesTab()
//		.verifyImagesTab("own", 8, 2, 0, false)
		.logout();
		
		
		
		
	}

}
