package kitchen.bryo.functionTest;

import org.openqa.selenium.support.PageFactory;
import org.testng.annotations.Test;

import hbm.planner.dataobject.SignUpData;
import hbm.planner.utility.Browser;
import hbm.planner.utility.UtilHBM;
import kitchen.bryo.pageObject.StartNow;

public class ComposeYourFurniture extends Browser {
	@Test(dataProvider = "bryoLogin", dataProviderClass = SignUpData.class)
	public void composeFurnitureTest(SignUpData signUpData){
		StartNow start = PageFactory.initElements(driver, StartNow.class);
		start.startDemo("en-GB")
		.startFromScratch()
		.step3()
		.verifyPrice("0,00")
		.addProduct("GMO032", true, false, false)
		.addProperty(-130,-40, "Top Cover Panel", "CONCORDE|15770", "", true)	
		.verifyAddProperty(-130,-40, "Top Cover Panel","CONCORDE|15770")
		.replaceProperty(-130,-40, "Right Cover Panel", "CONCORDE|16050", "",true, "")
		.verifyReplaceProperty(-130,-40, "Right Cover Panel","CONCORDE|16050")
		.customiseProduct(-130,-40, "1 264,00")
//		.composeFurniturePrice("1 268,00")
		.deleteComposeProduct(154,-217)
		.displayFront()
		.openCabinet()
//		customise.addItemInCabinet("4");
//		customise.verifyAddedItemInCabinet(106,-246, "INTERNAL DRAWER 100");
		.addItemInCabinet("INTERNAL DRAWER 100", true)
		.displayFront()
		.openCabinet()
		.verifyAddedItemInCabinet(95, -308, "INTERNAL DRAWER 100")
		.addItemInCabinet("DOOR 600", false)
		.verifyAddedItemInCabinet(154,-217, "DOOR 600")
		.editComposeReplaceProperty(154,-217, "Front", "CONCORDE|14119",false)
		.verifyComposeReplaceProperty(154,-217,"Front", "CONCORDE|14119")
		.editComposeReplaceProperty(154,-217, "Front", "OPERA|15516",false)
		.verifyComposeReplaceProperty(154,-217,"Front", "OPERA|15516")
		.undoInCompose(5)
		.verifyComposeReplaceProperty(154,-217,"Front", "CONCORDE|14119")
		.validateComposeFurniture()
		.verifyComposedProduct(-9,-87)
		.replaceProperty(-9,-87, "Right Cover Panel","OPERA|16054", "",true, "")
		.verifyReplaceProperty(-9,-87, "Right Cover Panel","OPERA|16054")
		.twoDView()
		.threeDView()
		.addProduct("U2DA80", true, false, false)
		.customiseProductThroughReplace(48,10, "")
		.editComposeReplaceProperty(150,0, "Front", "OPERA|15762",false)
		.verifyComposeReplaceProperty(150,0, "Front","OPERA|15762")
		.editComposeReplaceProperty(165,120, "Front", "OPERA|15762",false)
		.verifyComposeReplaceProperty(165,120,"Front", "OPERA|15762")
		.validateComposeFurniture()
		.verifyComposedProduct(-2,14)
		.addProduct("CKT800", true, false, false)
		.customiseProduct(38,19, "1 428,00")
		.deleteComposeProduct(142,7)
		.deleteComposeProduct(156,123)
		.addItemInCabinet("DOOR 800", false)
		.verifyAddedItemInCabinet(151,40, "DOOR 800")
		.handleOrientation(151, 40, "Horizontal")
		.verifyHandleOrientation(151, 40, "Horizontal")
		.editComposeReplaceProperty(82, 88, "Front", "CONCORDE|14119",false)
//		.replaceAppliancesInCompose(-11, -134, "COOKTOP", "JEAN BAPTISTE",false)
//		.verifyReplaceAppliancesInCompose(-11, -134, "JEAN BAPTISTE")
		.validateComposeFurniture()
		.verifyComposedProduct(26,13)
		.addProductThroughSearch("SPUD80", "SPUD80", true, false)
		.customiseProduct(78,13, "1 036,98")
		.deleteComposeProduct(29,60)
		.addItemInCabinet("DRAWER 400", false)
		.verifyAddedItemInCabinet(125,-3, "DRAWER 400")
		.addItemInCabinet("DRAWER 400", false)
		.verifyAddedItemInCabinet(105,106, "DRAWER 400")
		.undoInCompose(2)
		.redoInCompose(2)
		.verifyAddedItemInCabinet(122,106, "DRAWER 400")
		.replaceAppliancesInCompose(7, -88, "87109", "LOPEN",false)
		.verifyReplaceAppliancesInCompose(7, -88, "LOPEN")
		.replaceAppliancesInCompose(-25, -127, "BENOIT", "MANU",false)
		.verifyReplaceAppliancesInCompose(-25, -127, "MANU")
		.validateComposeFurniture()
		.verifyComposedProduct(46,5)
		.verifyReplaceProperty(46,5, "Sink", "LOPEN")
		.verifyReplaceProperty(46,5, "Faucet", "MANU")
		.addProduct("U2DA80", true, false, false)
		.replaceProperty(100,15, "Front", "CONCORDE|15765", "", true,"")
		.verifyReplaceProperty(100,15, "Front", "CONCORDE|15765")
		.customiseProduct(100,15, "")
		.addItemInCabinet("INTERNAL DRAWER 100", false)
		.verifyAddedItemInCabinet(35, -37, "INTERNAL DRAWER 100")
		.undoInCompose(2)
		.deleteComposeProduct(151,40)
		.deleteComposeProduct(187,145)
		.addItemInCabinet("DRAWER 400", false)
		.verifyAddedItemInCabinet(88,-19, "DRAWER 400")
		.addItemInCabinet("DRAWER 400", false)
		.verifyAddedItemInCabinet(125,97, "DRAWER 400")
		.validateComposeFurniture()
		.verifyComposedProduct(100,15)
		.addProduct("W6002", true, true, false)
		.verifyReplaceProperty(100,-95, "Front", "CONCORDE|15764")
		.customiseProduct(100,-95, "285,00")
		.deleteComposeProduct(63, 87)
		.zoomIn(5)
		.elevateProduct(46,-14, 65, -109)
		.addItemInCabinet("NANTES", false)
		.verifyAddedItemInCabinet(29, -61, "NANTES")
		.zoomOut(2)
		.addItemInCabinet("LIFT DOOR 400", false)
		.verifyAddedItemInCabinet(141, -98, "LIFT DOOR 400")
		.addItemInCabinet("DOOR 400", false)
		.verifyAddedItemInCabinet(134, 221, "DOOR 400")
		.validateComposeFurniture()
		.verifyComposedProduct(100,-95)
		.saveProjectInStep3(signUpData, "ODT_CUSTOM_PRODUCT_TEST" + UtilHBM.getDate(0, "yyyyMMdd"),"Custom product test " + UtilHBM.getDate(0, "yyyyMMdd"))
		.closePlanner()
		.openMyProjectList()
		.searchProject("ODT_CUSTOM_PRODUCT_TEST" + UtilHBM.getDate(0, "yyyyMMdd"))
//		.openProject()
		.openProject(0, "ODT_CUSTOM_PRODUCT_TEST" + UtilHBM.getDate(0, "yyyyMMdd"))
		.verifyPrice("8 881,00")
		.customiseProduct(-274, 12, "1 460,00")
		.verifyComposeReplaceProperty(154,-217,"Front", "CONCORDE|14119")
		.cancelComposeFurniture()
		.verifyPrice("8 881,00");

	}
}
