
package kitchen.bryo.functionTest;

import hbm.planner.dataobject.SignUpData;
import hbm.planner.utility.Browser;
import kitchen.bryo.pageObject.StartNow;
import org.openqa.selenium.support.PageFactory;
import org.testng.annotations.Test;

/*
	FUN118344 : As a user, I want to be able to modify cabinet dimensions in the planner
 */
public class ModifyCabinetsDimensions extends Browser {
	@Test(dataProvider = "bryoLogin", dataProviderClass = SignUpData.class)
	public void modifyCabinetsDimensions(SignUpData signUpData){
		StartNow start = PageFactory.initElements(driver, StartNow.class);
		start.startDemo("en-GB")
				.startFromScratch()
				.step3()
				.verifyPrice("0,00")
				.addProduct("U2DA80", true, true,false)
				/*Standalone cabinet :
				1. Verify dims editable if its set to editable in 3DCloudByme
				2. No collision with wall while resizing - verifying with cabinet position as Item Position BR is still triggered if say.. drawers are not resizable
				*/
				.selectProduct(-100, -15).editProperty().verifyFurnitureDimensionEditable("true:continuous","true:discrete","false")
				.verifyPosition(-100, -15,"3137 mm")
				.verifyPosition(-100, -15,"3351 mm")
				.replaceProperty(-100,-15,"Drawer Front", "MADELEINE|15514","",true,"")
				.selectProduct(-100, -15).editProperty().editFurniture("385","600","")
				.selectProduct(-100, -15).editProperty().verifyFurnitureDimensions("385 mm","600 mm","")
				.verifyPosition(-100, -15,"50 mm")
				.verifyPosition(-100, -15,"3337 mm")
				.verifyPosition(-100, -15,"3566 mm")

				//3. Cabinet properties retained after resize
				.verifyReplaceProperty(-100,-15,"Drawer Front", "MADELEINE|15514")
				.verifyReplaceProperty(-100,-15,"Plinth Option", "MADELEINE|13950")
				.verifyReplaceProperty(-100,-15,"Worktop Option", "WOOD OAK")
				.verifyReplaceProperty(-100,-15,"Right Cover Panel", "MADELEINE|13857")

				//4. Limits/options set on cabinet dimensions work when resizing in the planner
				.selectProduct(-100, -15).editProperty().editFurniture("600","800","")
				.selectProduct(-100, -15).editProperty().verifyFurnitureDimensions("600 mm","800 mm","")
				.verifyPosition(-100, -15,"3187 mm")
				.verifyPosition(-100, -15,"3351 mm")

				.selectProduct(-100, -15).editProperty().editFurniture("369","","").verifyErrorMessage("depth", "The minimum value is 370.")
				.selectProduct(-100, -15).editProperty().editFurniture("601","","").verifyErrorMessage("depth", "The maximum value is 600.")
				.selectProduct(-100, -15).editProperty().verifyPossibleValues("width", "800 mm > 600 mm")
				.translateProduct(1,1);
		//4. Fillers autogenerated appropriately (?)


		/*Cabinet within Linear:
		 */

		//TODO : TBD
	}
}
