package kitchen.bryo.functionTest;

import hbm.planner.utility.Browser;
import kitchen.bryo.pageObject.HomePage;
import kitchen.bryo.pageObject.StartNow;
import org.openqa.selenium.support.PageFactory;
import org.testng.annotations.Test;

/**
 * KIT-1722 :  Verify WT move after customize
 */

public class WorktopMoveCustomizedWT extends Browser {
    @Test
    public void worktopMoveCustomizedWT() {
    	StartNow start=PageFactory.initElements(driver, StartNow.class);
    	start.startDemo("en-GB");
        HomePage home = PageFactory.initElements(driver, HomePage.class);
        home.startKitchenDesign()
                .selectStyleMapping("Paris - White", "38mm Laminate Worktop", "234mm Bar Handle")
                .layoutMapping("L-Shaped").cookingMapping("").refrigerationMapping("").startPlanning()
                .nextStep()
                .waterSupplyPositionPopUp("No", 0, 0)
                .findSolutions("88 - L Shaped kitchen")
                .nextStepDesignYourKitchen("No", "")
                .twoDView().threeDView()

                //Scenario : move worktop after customizing it on a linear generated by template
                .worktopEditor(-98,52)
                .editWorktopYes()
                .createCutOut(175,20, "Rectangle", "150 mm", "150 mm", "", "", "")
                .validateWorktopEditor()
                .twoDView().threeDView()
                 .verifyProduct(-115,40, "LAMINATE BLACK")
                .translateProduct(-115,40,20,100).clickBlank()
                 .verifyProduct(-55,70, "LAMINATE BLACK")
                .verifyProduct(-115,40, "UD2SA100")
                .verifyReplaceProperty(-115,40, "Worktop", "LAMINATE BLACK")

                //Scenario : move customized worktops which comes as default when adding cabinets
                .twoDView().emptyRoom(-90, -110, "KITCHEN", "16.0 m²", "Yes").threeDView()
                .addProduct("U2DA602", true, true, false)
                .addProduct("U2DA80", true, true, false)
                .worktopEditor(-70,-45)
                .editWorktopYes()
                .createCutOut(-105,-195, "Rectangle", "200 mm", "200 mm", "", "", "")
                .validateWorktopEditor()
                .twoDView().threeDView()
                .verifyProduct(-20,-20, "LAMINATE BLACK")
                .translateProduct(-20,-20,20,100).clickBlank()
                .verifyProduct(-20,-20, "U2DA602")
                .verifyProduct(0,80, "LAMINATE BLACK")
                .verifyReplaceProperty(-20,-20, "Worktop", "LAMINATE BLACK")


//                Scenario : move  freestanding worktop after customization
                .twoDView().emptyRoom(20,-60, "KITCHEN", "16.0 m²", "Yes").threeDView()
                .addProductThroughSearch("Worktop", "ACRYLIC WHITE", true, false)
                .modifyFreestandingWorktop(-10,40,"")
                .editWorktopYes()
                .createCutOut(-17,-13, "Rectangle", "200 mm", "200 mm", "", "", "")
                .validateWorktopEditor()
                .twoDView().threeDView()
                .translateProduct(15,40,0,100).clickBlank()
                .verifyProduct(25, 140, "ACRYLIC WHITE");
    }
}
