package hbm.planner.utility;

public class Setting {

	public static String imgPath = "./src/test/StaticImages/";
	public static String threeDModelsPath = "./src/test/resources/3Dmodels/";
	public static String catalogPath = "./src/test/resources/catalog.data";
	public static String bryoINLCatalogPath = "./src/test/resources/bryoINLCatalog.data";
	public static String bryoCatalogPath = "./src/test/resources/bryoCatalog.data";
	public static String catalogPreprodPath = "./src/test/resources/catalogPreprod.data";
	public static String wallParametersPath = "./src/test/resources/wallParameters.txt";
	public static String testCatalogPath= "./src/test/resources/";
	public static String threeDBlankimgPath = "./src/test/StaticImages/3DBlank1.png";
	public static String twoDBlankimgPath = "./src/test/StaticImages/2DBlank.png";
	public static String BlankimgPath = "./src/test/StaticImages/BlankSpace.png";
	public static String prodLink = "https://home.by.me";
	public static String preProdLink = "https://preprod-home.by.me";
	public static String preProd = "https://preprod-home.by.me";
	public static String preprod3dPlanByMeLink = "https://preprod-platform.by.me";
//	public static String preprodCloudFrontLink = "https://homebyme:betatest1@d31ax5swi3lxrl.cloudfront.net";
	public static String relLink = "https://homebyme:betatest1@rel-home.by.me";
	public static String rel3dPlanByMeLink = "https://homebyme:betatest1@rel-platform.by.me";
	public static String rel = "https://rel-home.by.me";
	public static String partnerPlanner = "https://homebyme:betatest1@preprod-home.by.me/en/partner/view-project/1034";
	public static String bryo="https://bryo.enterprise.by.me/en-GB";
	public static String bryoPlanner="https://kitchen.enterprise.by.me";
	public static String bryoStaging="https://staging-bryo.enterprise.by.me/en-GB";
	public static String bryoPreprodStaging="https://preprod-staging-bryo.enterprise-dev.by.me/en-GB/";
	public static String bryoPlannerStaging="https://staging-kitchen.enterprise.by.me";
	public static String bryoPreprod="https://preprod-bryo.enterprise-dev.by.me/en-GB";
	public static String bryoPlannerPreprod="https://preprod-kitchen.enterprise-dev.by.me";
	public static String ikeaPlanner="https://preprod-staging-kitchen.ikea.by.me/";
	public static String mobileKitchen="https://preprod-kitchen.enterprise-dev.by.me?kitchenAlpha";
	public static String bryoPreprodBeta="https://preprod-bryo.enterprise-dev.by.me/en-GB?kitchenBeta";
	public static String bryoPreprodAlpha="https://preprod-bryo.enterprise-dev.by.me/en-GB?kitchenAlpha";
	public static String bryoPlannerPreprodBeta="https://preprod-kitchen.enterprise-dev.by.me?kitchenBeta";
	public static String bryoWidget="https://widgeted:widgeting@preprod-widgets.enterprise-dev.by.me/MyProjectsView/embed.html";
	public static String cloud="https://homebyme:betatest1@preprod-3dcloud.by.me/en/";
	public static String newCloud="https://preprod-3dcloud.by.me/en/login?alpha=openID";
	public static String entPreprodNewCloud="https://preprod-staging-3dcloud.enterprise-dev.by.me/en/login?alpha=openID";
	public static String entPreprodStagingCloud="https://preprod-staging-3dcloud.enterprise-dev.by.me/en/login";
	public static String entPreprodCloud="https://preprod-3dcloud.enterprise-dev.by.me/en/login";
	public static String teRel="https://preprod-kitchen.enterprise-dev.by.me/template.html";
	public static String tePreprod="https://preprod-kitchen.enterprise-dev.by.me/template.html";
	public static String hyperlinks = "./src/test/resources/WebTest.links";
	public static String screenCapturePath = "./screenCaptures/";
	public static String threeDCloudData="./src/test/threeDCloudData/";
	public static String threeDCloudTestParameter="./src/test/resources/3DCloudByMe.data";
	public static String htmlRefPreprod = "./src/test/resources/htmlRefPreprod/";
	public static String htmlOutPreprod = "./src/test/resources/htmlOutPreprod/";
	public static String draftsightEmbed = "https://preprod-home.by.me/component/embed/user/project/list?close=false&signup=false&hideSignUp";
	public static String templateEditorParameter="./src/test/resources/TemplateEditor.data";
	public static String mdmpreprod="https://preprod-home.by.me/en/partner/gautier";	
	public static String testDatapath="./src/test/resources/";		
	public static String platformDev= "https://homebyme:betatest1@preprod-platform.by.me/?ln=en";
	public static String stagingAssemblyEditor="https://kitchenbyme:Next!Gen01@preprod-staging-assembly.enterprise-dev.by.me/";
	public static String teCatalog="./src/test/resources/";
	public static String embedHBMProjects= "./src/main/resources/HBMProject.html";
	public static String hrPlannerPreprod="https://retailinghomes:dropd2019@preprod-home.enterprise-dev.by.me";
	public static String hrWebPreprod= "https://bryohome:homingbryo@preprod-bryohome.enterprise-dev.by.me/en-GB/";
	public static String hrWebPreprodStaging= "https://bryohome:homingbryo@preprod-staging-bryohome.enterprise-dev.by.me/en-GB/";
	public static String hrUSWebPreprod= "https://bryohome:homingbryo@preprod-bryohome.enterprise-dev.by.me/en-US/";
	public static String hrWidgetPreprod= "https://widgeted:widgeting@preprod-widgets.enterprise-dev.by.me/MyProjectsView/embed.html";
	public static String enterpriseBuildId = "https://preprod-kitchen.enterprise-dev.by.me/ping/";
	public static String enterpriseStagingBuildId = "https://preprod-staging-kitchen.enterprise-dev.by.me/ping/";
	public static String hbmBuildId = "https://homebyme:betatest1@preprod-home.by.me/ping";
	public static String bathroomPreprod = "https://preprod-staging-bathroom.enterprise-dev.by.me/";
	public static String bryoBathroomCatalogPath = "./src/test/resources/bryoBathroomCatalog.txt";
	public static String bathroomImg = "./src/test/StaticImages/";
}
